In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import os
import pandas as pd
import seaborn as sns
import numpy as np
import random
from matplotlib import pyplot as plt
from datetime import datetime
%matplotlib inline

import warnings
warnings.filterwarnings('ignore')

In [7]:
# 뮤지컬 csv
data1 = pd.read_excel('/content/drive/MyDrive/캡스톤 디자인/인터파크/연극_평점 (최종).xlsx')
data1 = data1.drop(data1.columns[0], axis=1)
data1.head()

           Title            ID  Star        Date
0  연극 너의 목소리가 들려  darkness1***     5  2023.10.11
1  연극 너의 목소리가 들려     mangdd***     5  2023.10.10
2  연극 너의 목소리가 들려          p***     5  2023.10.10
3  연극 너의 목소리가 들려       bbb8***     5  2023.10.10
4  연극 너의 목소리가 들려    tkdkf02***     5  2023.10.09

In [8]:
n_user = len(data1['ID'].unique())    # 유저 수
n_movie = len(data1['Title'].unique())    # 영화 수

print('유저 수 :', n_user, '영화 수 :', n_movie)

# 평점 데이터 정보
data1.info()

유저 수 : 6363 영화 수 : 40
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9760 entries, 0 to 9759
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Title   9760 non-null   object
 1   ID      9760 non-null   object
 2   Star    9760 non-null   int64
 3   Date    9760 non-null   object
dtypes: int64(1), object(3)
memory usage: 305.1+ KB

In [12]:
play_statistics1 = pd.DataFrame({
    'numUsers': data1.groupby('Title')['ID'].nunique(),
    'avgRating': data1.groupby('Title')['Star'].mean(),
    'stdRating': data1.groupby('Title')['Star'].std()
}).reset_index()

play_statistics1

                               Title  numUsers  avgRating  stdRating
0            !로맨틱코미디 연극〈운빨로맨스〉! - 대구        22   5.000000   0.000000
1             (리얼타임 코믹연극) 택시안에서 - 부산        35   4.767442   0.718371
2             (리얼타임 코믹연극) 택시안에서 - 서울       144   4.744076   0.648001
3                      (코믹연극) 달동네-부산        13   4.928571   0.267261
4          10년 연속 1위 연극〈옥탑방고양이〉- 틴틴홀       431   4.819608   0.580299
5                          2시간탈출 졸탄쇼       125   4.772059   0.698855
6              3대가 웃고 우는 연극 〈염쟁이 유씨〉        13   4.923077   0.277350
7                       4D공포연극 〈스위치〉       337   4.955556   0.273759
8                ★평점9.5★ 코미디의맛/쇼미더퍼니       294   4.764045   0.710641
9                   공포스릴러연극〈두여자〉- 대구        56   5.000000   0.000000
10                           공포연극 조각       118   4.789062   0.749302
11                         공포연극 ［자취］       141   4.810000   0.667930
12  국민 코믹 연극 〈오백에삼십〉 - 대학로 세우아트센터 1관       487   4.896673   0.429001
13                           그곳에 있었다        11   4.818182   0.404520
14                        나의 장례식에 와줘        14   4.928571   0.267261
15                대학로 1위 연극 〈쉬어매드니스〉       287   4.760784   0.547930
16                대학로 청소년연극 〈사춘기메들리〉       133   4.944444   0.284268
17                로맨틱코미디 〈슬기로운 신혼생활〉       103   4.898148   0.333204
18                        모든 날 모든 순간        14   4.937500   0.250000
19                   뮤직드라마 〈불편한 편의점〉       227   4.717300   0.719166
20                          연극 〈굿닥터〉        27   4.814815   0.395847
21                      연극 〈극적인 하룻밤〉        24   4.720000   0.783503
22                      연극 〈나의PS파트너〉        38   4.937500   0.244623
23                       연극 〈뷰티풀라이프〉       377   4.936170   0.274545
24                       연극 〈수상한흥신소〉        59   4.968750   0.175368
25                   연극 〈운빨로맨스〉- 대학로       495   4.907303   0.433937
26                      연극 〈카페 쥬에네스〉        93   4.009901   1.410639
27                     연극 너의 목소리가 들려       310   4.986301   0.116370
28                       연극 죽여주는 이야기       234   4.971875   0.242420
29                           연극 한뼘사이       459   4.913478   0.431086
30                            연극 핫식스       234   4.967626   0.273423
31                       연극〈늘근도둑이야기〉       461   4.811765   0.675024
32                       이머시브씨어터 카지노       132   4.903571   0.441553
33                         좀비연극 오마이갓       336   4.966346   0.257555
34                            진짜나쁜소녀       106   4.779412   0.747254
35                      코미디 연극〈딜리버리〉        43   4.723404   0.852162
36           코믹감동 휴먼판타지 연극 〈2호선 세입자〉       509   4.601639   0.873058
37                               행오버       180   4.746269   0.748531
38      ［2023 SPAF］ 극단 돌파구 〈지상의 여자들〉        20   4.650000   0.587143
39                     ［서울 대학로］연극 라면       423   4.896970   0.458270

# 장르별 추천유사도

In [13]:
play_statistics1

                               Title  numUsers  avgRating  stdRating
0            !로맨틱코미디 연극〈운빨로맨스〉! - 대구        22   5.000000   0.000000
1             (리얼타임 코믹연극) 택시안에서 - 부산        35   4.767442   0.718371
2             (리얼타임 코믹연극) 택시안에서 - 서울       144   4.744076   0.648001
3                      (코믹연극) 달동네-부산        13   4.928571   0.267261
4          10년 연속 1위 연극〈옥탑방고양이〉- 틴틴홀       431   4.819608   0.580299
5                          2시간탈출 졸탄쇼       125   4.772059   0.698855
6              3대가 웃고 우는 연극 〈염쟁이 유씨〉        13   4.923077   0.277350
7                       4D공포연극 〈스위치〉       337   4.955556   0.273759
8                ★평점9.5★ 코미디의맛/쇼미더퍼니       294   4.764045   0.710641
9                   공포스릴러연극〈두여자〉- 대구        56   5.000000   0.000000
10                           공포연극 조각       118   4.789062   0.749302
11                         공포연극 ［자취］       141   4.810000   0.667930
12  국민 코믹 연극 〈오백에삼십〉 - 대학로 세우아트센터 1관       487   4.896673   0.429001
13                           그곳에 있었다        11   4.818182   0.404520
14                        나의 장례식에 와줘        14   4.928571   0.267261
15                대학로 1위 연극 〈쉬어매드니스〉       287   4.760784   0.547930
16                대학로 청소년연극 〈사춘기메들리〉       133   4.944444   0.284268
17                로맨틱코미디 〈슬기로운 신혼생활〉       103   4.898148   0.333204
18                        모든 날 모든 순간        14   4.937500   0.250000
19                   뮤직드라마 〈불편한 편의점〉       227   4.717300   0.719166
20                          연극 〈굿닥터〉        27   4.814815   0.395847
21                      연극 〈극적인 하룻밤〉        24   4.720000   0.783503
22                      연극 〈나의PS파트너〉        38   4.937500   0.244623
23                       연극 〈뷰티풀라이프〉       377   4.936170   0.274545
24                       연극 〈수상한흥신소〉        59   4.968750   0.175368
25                   연극 〈운빨로맨스〉- 대학로       495   4.907303   0.433937
26                      연극 〈카페 쥬에네스〉        93   4.009901   1.410639
27                     연극 너의 목소리가 들려       310   4.986301   0.116370
28                       연극 죽여주는 이야기       234   4.971875   0.242420
29                           연극 한뼘사이       459   4.913478   0.431086
30                            연극 핫식스       234   4.967626   0.273423
31                       연극〈늘근도둑이야기〉       461   4.811765   0.675024
32                       이머시브씨어터 카지노       132   4.903571   0.441553
33                         좀비연극 오마이갓       336   4.966346   0.257555
34                            진짜나쁜소녀       106   4.779412   0.747254
35                      코미디 연극〈딜리버리〉        43   4.723404   0.852162
36           코믹감동 휴먼판타지 연극 〈2호선 세입자〉       509   4.601639   0.873058
37                               행오버       180   4.746269   0.748531
38      ［2023 SPAF］ 극단 돌파구 〈지상의 여자들〉        20   4.650000   0.587143
39                     ［서울 대학로］연극 라면       423   4.896970   0.458270

In [15]:
# 연극 csv
df0 = pd.read_excel('/content/drive/MyDrive/캡스톤 디자인/인터파크/연극병합.xlsx')
df0 = df0.drop(df0.columns[0], axis=1)
df0=df0[['Title','장르']]
df0

                         Title           장르
0      !로맨틱코미디 연극〈운빨로맨스〉! - 대구      로맨스, 코믹
1       (리얼타임 코믹연극) 택시안에서 - 부산      코믹, 로맨스
2       (리얼타임 코믹연극) 택시안에서 - 서울      코믹, 로맨스
3                (코믹연극) 달동네-부산  코믹, 감동, 드라마
4    10년 연속 1위 연극〈옥탑방고양이〉- 틴틴홀      로맨스, 코믹
..                         ...          ...
151     ［연극 on stage］ 띨뿌리 - 화성          역사극
152    ［연애하기 좋은 날 : 당근거래］ - 전주          로맨스
153       ［장애인 선예매］ 러브 앤 인포메이션          역사극
154        ［창작공감: 연출］당신에게 닿는 길      판타지,드라마
155        ［청소년극］［Tank ; 0-24］          드라마

[156 rows x 2 columns]

In [16]:
df=df0.merge(play_statistics1,how='left',on='Title')
df

                         Title           장르  numUsers  avgRating  stdRating
0      !로맨틱코미디 연극〈운빨로맨스〉! - 대구      로맨스, 코믹      22.0   5.000000   0.000000
1       (리얼타임 코믹연극) 택시안에서 - 부산      코믹, 로맨스      35.0   4.767442   0.718371
2       (리얼타임 코믹연극) 택시안에서 - 서울      코믹, 로맨스     144.0   4.744076   0.648001
3                (코믹연극) 달동네-부산  코믹, 감동, 드라마      13.0   4.928571   0.267261
4    10년 연속 1위 연극〈옥탑방고양이〉- 틴틴홀      로맨스, 코믹     431.0   4.819608   0.580299
..                         ...          ...       ...        ...        ...
151     ［연극 on stage］ 띨뿌리 - 화성          역사극       NaN        NaN        NaN
152    ［연애하기 좋은 날 : 당근거래］ - 전주          로맨스       NaN        NaN        NaN
153       ［장애인 선예매］ 러브 앤 인포메이션          역사극       NaN        NaN        NaN
154        ［창작공감: 연출］당신에게 닿는 길      판타지,드라마       NaN        NaN        NaN
155        ［청소년극］［Tank ; 0-24］          드라마       NaN        NaN        NaN

[156 rows x 5 columns]

In [17]:
df.isna().sum()

Title          0
장르             0
numUsers     116
avgRating    116
stdRating    116
dtype: int64

##TF

In [18]:
from sklearn.feature_extraction.text import CountVectorizer

#df 장르에 존재하는 공백 형식이 갖추어지지 않아있어서 공백있는거 공백 제거하기
df['장르']=df['장르'].str.replace(' ', '').str.replace(',', ', ')

#그 다음 ,를 기준으로 장르 나눠주기
df['genres_literal']=df['장르'].str.split(',')
df['genres_literal'] = df['genres_literal'].apply(lambda x : (' ').join(x))

count_vect = CountVectorizer(min_df=0, ngram_range=(1,2)) #우리가 지금 CountVectorizer 쓸거야.
genre_mat = count_vect.fit_transform(df['genres_literal'])

print(genre_mat.shape)

(156, 59)

In [20]:
df=df[['Title', '장르','genres_literal', 'numUsers', 'avgRating', 'stdRating']]
df

,Title,장르,genres_literal,numUsers,avgRating,stdRating
0,!로맨틱코미디 연극〈운빨로맨스〉! - 대구,"로맨스, 코믹",로맨스 코믹,22.0,5.000000,0.000000
1,(리얼타임 코믹연극) 택시안에서 - 부산,"코믹, 로맨스",코믹 로맨스,35.0,4.767442,0.718371
2,(리얼타임 코믹연극) 택시안에서 - 서울,"코믹, 로맨스",코믹 로맨스,144.0,4.744076,0.648001
3,(코믹연극) 달동네-부산,"코믹, 감동, 드라마",코믹 감동 드라마,13.0,4.928571,0.267261
4,10년 연속 1위 연극〈옥탑방고양이〉- 틴틴홀,"로맨스, 코믹",로맨스 코믹,431.0,4.819608,0.580299
...,...,...,...,...,...,...
151,［연극 on stage］ 띨뿌리 - 화성,역사극,역사극,NaN,NaN,NaN
152,［연애하기 좋은 날 : 당근거래］ - 전주,로맨스,로맨스,NaN,NaN,NaN
153,［장애인 선예매］ 러브 앤 인포메이션,역사극,역사극,NaN,NaN,NaN
154,［창작공감: 연출］당신에게 닿는 길,"판타지, 드라마",판타지 드라마,NaN,NaN,NaN
155,［청소년극］［Tank ; 0-24］,드라마,드라마,NaN,NaN,NaN

In [21]:
print(genre_mat)

  (0, 20)	1
  (0, 48)	1
  (0, 26)	1
  (1, 20)	1
  (1, 48)	1
  (1, 51)	1
  (2, 20)	1
  (2, 48)	1
  (2, 51)	1
  (3, 48)	1
  (3, 2)	1
  (3, 10)	1
  (3, 49)	1
  (3, 3)	1
  (4, 20)	1
  (4, 48)	1
  (4, 26)	1
  (5, 2)	1
  (5, 10)	1
  (5, 3)	1
  (6, 2)	1
  (6, 10)	1
  (6, 11)	1
  (7, 48)	1
  (8, 2)	1
  :	:
  (145, 25)	1
  (146, 20)	1
  (146, 43)	1
  (146, 25)	1
  (147, 20)	1
  (147, 43)	1
  (147, 25)	1
  (148, 20)	1
  (148, 43)	1
  (148, 25)	1
  (149, 20)	1
  (149, 43)	1
  (149, 25)	1
  (150, 10)	1
  (150, 32)	1
  (150, 33)	1
  (150, 30)	1
  (150, 14)	1
  (151, 38)	1
  (152, 20)	1
  (153, 38)	1
  (154, 10)	1
  (154, 53)	1
  (154, 55)	1
  (155, 10)	1

###코사인 유사도(TF)

In [22]:
from sklearn.metrics.pairwise import cosine_similarity

genre_sim = cosine_similarity(genre_mat, genre_mat)#똑같은 메트릭스를 두개 집어넣는다.
print(genre_sim.shape)

(156, 156)

In [23]:
genre_sim_sorted_ind = genre_sim.argsort()[:, ::-1] #내림차순으로 sorting해서 보여줘.
print(genre_sim_sorted_ind[:1]) #영화 번호들 나옴

[[  0  82   4  68  71   1   2   7  19  25  72  81  77 152  88 142 141 113
  105  87 143 144 145  70 119 147  55  53 148  20 149 117 146 140 125  24
   60  97  94  69 101 126 107  86  96 112  50  51   3 118  84  39  33  31
   34  35  36  37  38  32  42  40  41  29  43  44  45  46  47  48  49  52
   30 122  28  14 153 151   5   6 150   8   9  10  11  12  13  15  27  16
   17  18 139 138  21  22  23  54 137  26 136  61 135 103 127  89  90  91
   92  93  95  98  99 100 102 104  56 106 108 109 110 111 114 115 116 124
  123 120 128  85  83 129  57  58  59 121  62  63  64  65  66  67 134 133
  132 131  73  74  75  76 154  78  79  80 130 155]]

In [24]:
def find_sim_movie(df, sorted_ind, title_name, top_n=10):

    # 인자로 입력된 movies_df DataFrame에서 'title' 컬럼이 입력된 title_name 값인 DataFrame추출
    title_movie = df[df['Title'] == title_name]

    # title_named을 가진 DataFrame의 index 객체를 ndarray로 반환하고
    # sorted_ind 인자로 입력된 genre_sim_sorted_ind 객체에서 유사도 순으로 top_n 개의 index 추출
    title_index = title_movie.index.values
    similar_indexes = sorted_ind[title_index, :(top_n)]

    # 추출된 top_n index들 출력. top_n index는 2차원 데이터 임.
    #dataframe에서 index로 사용하기 위해서 1차원 array로 변경
    print(similar_indexes)
    similar_indexes = similar_indexes.reshape(-1)

    return df.iloc[similar_indexes]

In [34]:
similar_movies = find_sim_movie(df, genre_sim_sorted_ind, '(리얼타임 코믹연극) 택시안에서 - 부산',10)
similar_movies[['Title', 'avgRating']]

                         Title  avgRating
113            연극 〈운빨로맨스〉- 대학로   4.907303
72          대학로 청소년연극 〈사춘기메들리〉   4.944444
82          로맨틱코미디 〈슬기로운 신혼생활〉   4.898148
0      !로맨틱코미디 연극〈운빨로맨스〉! - 대구   5.000000
88                  모든 날 모든 순간   4.937500
4    10년 연속 1위 연극〈옥탑방고양이〉- 틴틴홀   4.819608
105               연극 〈극적인 하룻밤〉   4.720000
19                   2시간탈출 졸탄쇼   4.772059
2       (리얼타임 코믹연극) 택시안에서 - 서울   4.744076
25         ★평점9.5★ 코미디의맛/쇼미더퍼니   4.764045

In [35]:
df[['Title','avgRating','numUsers']].sort_values('avgRating', ascending=False)[:10]

                       Title  avgRating  numUsers
0    !로맨틱코미디 연극〈운빨로맨스〉! - 대구   5.000000      22.0
44          공포스릴러연극〈두여자〉- 대구   5.000000      56.0
115            연극 너의 목소리가 들려   4.986301     310.0
116              연극 죽여주는 이야기   4.971875     234.0
110              연극 〈수상한흥신소〉   4.968750      59.0
118                   연극 핫식스   4.967626     234.0
122                좀비연극 오마이갓   4.966346     336.0
23              4D공포연극 〈스위치〉   4.955556     337.0
72        대학로 청소년연극 〈사춘기메들리〉   4.944444     133.0
107             연극 〈나의PS파트너〉   4.937500      38.0

In [28]:
C = df['avgRating'].mean()
m = df['numUsers'].quantile(0.6)
print('C:',round(C,3), 'm:',round(m,3))

C: 4.835 m: 198.8

평점이 매겨진 대부분의 평균 별점은 4.85이상이고 평균 투표수는 198 이상이었다.

### 추천방식 1
몇 프로 이상되는 공연중에서만 추천해줘.

In [29]:
percentile = 0.6
m = df['numUsers'].quantile(percentile)
C = df['avgRating'].mean()

def weighted_avgRating(record):
    v = record['numUsers']
    R = record['avgRating']

    return ( (v/(v+m)) * R ) + ( (m/(m+v)) * C )

df['weighted_vote'] = df.apply(weighted_avgRating, axis=1)

In [30]:
df[['Title','avgRating','weighted_vote','numUsers']].sort_values('weighted_vote',
                                                                          ascending=False)[:10]

                                Title  avgRating  weighted_vote  numUsers
115                     연극 너의 목소리가 들려   4.986301       4.927069     310.0
122                         좀비연극 오마이갓   4.966346       4.917411     336.0
23                       4D공포연극 〈스위치〉   4.955556       4.910716     337.0
116                       연극 죽여주는 이야기   4.971875       4.908868     234.0
118                            연극 핫식스   4.967626       4.906571     234.0
109                       연극 〈뷰티풀라이프〉   4.936170       4.901138     377.0
117                           연극 한뼘사이   4.913478       4.889671     459.0
113                   연극 〈운빨로맨스〉- 대학로   4.907303       4.886501     495.0
50   국민 코믹 연극 〈오백에삼십〉 - 대학로 세우아트센터 1관   4.896673       4.878709     487.0
72                 대학로 청소년연극 〈사춘기메들리〉   4.944444       4.878693     133.0

### 추천방식 2-1(TF)

In [31]:
def find_sim_movie(df, sorted_ind, title_name, top_n=10):
    title_movie = df[df['Title'] == title_name]
    title_index = title_movie.index.values

    # top_n의 2배에 해당하는 쟝르 유사성이 높은 index 추출
    similar_indexes = sorted_ind[title_index, :(top_n*2)]
    similar_indexes = similar_indexes.reshape(-1)
    # 기준 영화 index는 제외
    similar_indexes = similar_indexes[similar_indexes != title_index]

    # top_n의 2배에 해당하는 후보군에서 weighted_vote 높은 순으로 top_n 만큼 추출
    return df.iloc[similar_indexes].sort_values('weighted_vote', ascending=False)[:top_n]

In [36]:
similar_movies = find_sim_movie(df, genre_sim_sorted_ind, '(리얼타임 코믹연극) 택시안에서 - 부산',10)
similar_movies[['Title', 'avgRating', 'weighted_vote']]

                         Title  avgRating  weighted_vote
113            연극 〈운빨로맨스〉- 대학로   4.907303       4.886501
72          대학로 청소년연극 〈사춘기메들리〉   4.944444       4.878693
82          로맨틱코미디 〈슬기로운 신혼생활〉   4.898148       4.856357
0      !로맨틱코미디 연극〈운빨로맨스〉! - 대구   5.000000       4.851174
88                  모든 날 모든 순간   4.937500       4.841468
4    10년 연속 1위 연극〈옥탑방고양이〉- 틴틴홀   4.819608       4.824373
105               연극 〈극적인 하룻밤〉   4.720000       4.822349
19                   2시간탈출 졸탄쇼   4.772059       4.810521
2       (리얼타임 코믹연극) 택시안에서 - 서울   4.744076       4.796634
25         ★평점9.5★ 코미디의맛/쇼미더퍼니   4.764045       4.792550

## TF-IDF

In [37]:
from sklearn.feature_extraction.text import TfidfVectorizer

#df 장르에 존재하는 공백 형식이 갖추어지지 않아있어서 공백있는거 공백 제거하기
df['장르']=df['장르'].str.replace(' ', '').str.replace(',', ', ')

#그 다음 ,를 기준으로 장르 나눠주기
df['genres_literal']=df['장르'].str.split(',')
df['genres_literal'] = df['genres_literal'].apply(lambda x : (' ').join(x))
#df
tfidf_vect = TfidfVectorizer()
genre_mat1=tfidf_vect.fit_transform(df['genres_literal'])

print(genre_mat1.shape)

(156, 14)

In [38]:
print(genre_mat1)

  (0, 12)	0.7372192659059431
  (0, 4)	0.6756535754194619
  (1, 12)	0.7372192659059431
  (1, 4)	0.6756535754194619
  (2, 12)	0.7372192659059431
  (2, 4)	0.6756535754194619
  (3, 3)	0.41153714613892745
  (3, 1)	0.5969460786617361
  (3, 12)	0.6886890129210742
  (4, 12)	0.7372192659059431
  (4, 4)	0.6756535754194619
  (5, 3)	0.5675929316515363
  (5, 1)	0.8233093367253977
  (6, 3)	0.5675929316515363
  (6, 1)	0.8233093367253977
  (7, 12)	1.0
  (8, 3)	0.5675929316515363
  (8, 1)	0.8233093367253977
  (9, 3)	0.5675929316515363
  (9, 1)	0.8233093367253977
  (10, 3)	0.5675929316515363
  (10, 1)	0.8233093367253977
  (11, 10)	0.7556444064171799
  (11, 1)	0.6549820845263081
  (12, 10)	0.7556444064171799
  :	:
  (142, 11)	0.7417696433795623
  (142, 4)	0.6706547518362611
  (143, 11)	0.7417696433795623
  (143, 4)	0.6706547518362611
  (144, 11)	0.7417696433795623
  (144, 4)	0.6706547518362611
  (145, 11)	0.7417696433795623
  (145, 4)	0.6706547518362611
  (146, 11)	0.7417696433795623
  (146, 4)	0.6706547518362611
  (147, 11)	0.7417696433795623
  (147, 4)	0.6706547518362611
  (148, 11)	0.7417696433795623
  (148, 4)	0.6706547518362611
  (149, 11)	0.7417696433795623
  (149, 4)	0.6706547518362611
  (150, 6)	0.8288109328920313
  (150, 8)	0.4980860371722536
  (150, 3)	0.25491711808484163
  (151, 10)	1.0
  (152, 4)	1.0
  (153, 10)	1.0
  (154, 13)	0.907841718989918
  (154, 3)	0.41931302538966136
  (155, 3)	1.0

###코사인 유사도(TF-IDF)

In [39]:
from sklearn.metrics.pairwise import cosine_similarity

genre_sim1 = cosine_similarity(genre_mat1, genre_mat1)#똑같은 메트릭스를 두개 집어넣는다.
print(genre_sim1.shape)

(156, 156)

In [40]:
genre_sim_sorted_ind1 = genre_sim1.argsort()[:, ::-1] #내림차순으로 sorting해서 보여줘.
print(genre_sim_sorted_ind1[:1]) #영화 번호들 나옴

[[  0   1   2   4  68  71  82  88   7  19  25  77  81 152  72  55  20  87
  125  60  51  96  24   3  70 144 145 105 143 147 142 117  53 148 149 113
  146 141 140 119  94 112  97  50  69 126  84  86 101 118 107  10  41  32
   33  34  35  36  37  38  39   5  40  42  30  43  44  45  46  47  48 151
   49 153 135  31  29  11  28  12  13   9  14  15  16  17  18   8 139 138
   21  22  23 137 136 134  26 150  27   6  52  59  54 102 123  89  90  91
   92  93  95 122  98  99 100 103 133 104 121 106 108 109 110 111 120 114
  115 116 124  85  83 127  56  57  58 132  61  62  63  64  65  66  67 131
  130 129 128  73  74  75  76 154  78  79  80 155]]

In [41]:
def find_sim_movie(df, sorted_ind, title_name, top_n=10):

    # 인자로 입력된 movies_df DataFrame에서 'title' 컬럼이 입력된 title_name 값인 DataFrame추출
    title_movie = df[df['Title'] == title_name]

    # title_named을 가진 DataFrame의 index 객체를 ndarray로 반환하고
    # sorted_ind 인자로 입력된 genre_sim_sorted_ind 객체에서 유사도 순으로 top_n 개의 index 추출
    title_index = title_movie.index.values
    similar_indexes = sorted_ind[title_index, :(top_n)]

    # 추출된 top_n index들 출력. top_n index는 2차원 데이터 임.
    #dataframe에서 index로 사용하기 위해서 1차원 array로 변경
    print(similar_indexes)
    similar_indexes = similar_indexes.reshape(-1)

    return df.iloc[similar_indexes]

In [45]:
similar_movies = find_sim_movie(df, genre_sim_sorted_ind1, '(리얼타임 코믹연극) 택시안에서 - 부산',10)
similar_movies[['Title', 'avgRating']]

[[ 0  1  2  4 68 71 82 88  7 19]]

                                Title  avgRating
0             !로맨틱코미디 연극〈운빨로맨스〉! - 대구   5.000000
1              (리얼타임 코믹연극) 택시안에서 - 부산   4.767442
2              (리얼타임 코믹연극) 택시안에서 - 서울   4.744076
4           10년 연속 1위 연극〈옥탑방고양이〉- 틴틴홀   4.819608
68         누구에게나 한번쯤 찾아오는 〈그날의,타이밍〉_B        NaN
71           대학로 대표 로코 연극 〈그날의,타이밍〉_J        NaN
82                 로맨틱코미디 〈슬기로운 신혼생활〉   4.898148
88                         모든 날 모든 순간   4.937500
7   2023 공유생 리:바운드 프로젝트 연극 〈오늘도 극한직업〉        NaN
19                          2시간탈출 졸탄쇼   4.772059

### 추천방식 2-2(TF-IDF)

In [48]:
def find_sim_movie(df, sorted_ind, title_name, top_n=10):
    title_movie = df[df['Title'] == title_name]
    title_index = title_movie.index.values

    # top_n의 2배에 해당하는 쟝르 유사성이 높은 index 추출
    similar_indexes = sorted_ind[title_index, :(top_n*2)]
    similar_indexes = similar_indexes.reshape(-1)
    # 기준 영화 index는 제외
    similar_indexes = similar_indexes[similar_indexes != title_index]

    # top_n의 2배에 해당하는 후보군에서 weighted_vote 높은 순으로 top_n 만큼 추출
    return df.iloc[similar_indexes].sort_values('weighted_vote', ascending=False)[:top_n]

In [49]:
similar_movies = find_sim_movie(df, genre_sim_sorted_ind1, '(리얼타임 코믹연극) 택시안에서 - 부산',10)
similar_movies[['Title', 'avgRating', 'weighted_vote']]

                         Title  avgRating  weighted_vote
72          대학로 청소년연극 〈사춘기메들리〉   4.944444       4.878693
82          로맨틱코미디 〈슬기로운 신혼생활〉   4.898148       4.856357
0      !로맨틱코미디 연극〈운빨로맨스〉! - 대구   5.000000       4.851174
88                  모든 날 모든 순간   4.937500       4.841468
60                  나의 장례식에 와줘   4.928571       4.840880
4    10년 연속 1위 연극〈옥탑방고양이〉- 틴틴홀   4.819608       4.824373
19                   2시간탈출 졸탄쇼   4.772059       4.810521
2       (리얼타임 코믹연극) 택시안에서 - 서울   4.744076       4.796634
25         ★평점9.5★ 코미디의맛/쇼미더퍼니   4.764045       4.792550
125    코믹감동 휴먼판타지 연극 〈2호선 세입자〉   4.601639       4.667101