In [1]:
import os
import time
import urllib.request
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
import pandas as pd
import numpy as np
from pytesseract import Output
import pytesseract
import cv2
import io
#import matplotlib.pyplot as plt

from selenium import webdriver
from selenium.webdriver.common.by import By
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.chrome.service import Service 
from bs4 import BeautifulSoup

import urllib.request

from selenium.webdriver.support.ui import WebDriverWait 
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.keys import Keys
from selenium.common.exceptions import NoSuchElementException

from PIL import Image, ImageOps, ImageFilter
from skimage import io
from skimage.filters import threshold_otsu
from skimage.morphology import remove_small_objects

## 이미지 크롤링 후 OCR 진행

In [20]:
def initialize_driver():
    chrome_options = webdriver.ChromeOptions()
    driver = webdriver.Chrome(service=Service('D:\chromedriver-win32\chromedriver.exe'), options=chrome_options)
    return driver


def get_theater_links(driver, query):
    driver.get(query)
    time.sleep(1)
    number = 150

    addresslist = []

    for i in range(1, int(number) + 1):
        xpath = f"/html/body/table/tbody/tr[2]/td[3]/div/div/div[2]/div/table/tbody/tr[{i}]/td[1]/a"
        elem = driver.find_element(By.XPATH, xpath).get_attribute("href")
        addresslist.append(elem)

    return addresslist


def resize_image(image, max_height):
    # 이미지 크기를 최대 높이에 맞춰 조정
    width_percent = (max_height / float(image.size[1]))
    new_width = int((float(image.size[0]) * float(width_percent)))
    resized_image = image.resize((new_width, max_height), Image.LANCZOS)
    return resized_image

def image(driver, addresslist, save_directory, max_image_height=2000):
    scraped_image = []
    for index, lis in enumerate(addresslist):
        driver.get(lis)
        time.sleep(1)
        
        # 이미지 요소 찾기
        img_area_elements = driver.find_elements(By.XPATH, '//*[@id="productMainBody"]/div/div/div[5]/div/p/strong/img')
        title_element = driver.find_element(By.XPATH, '//*[@id="container"]/div[5]/div[1]/div[2]/div[1]/div/div[1]/h2')
        
        # 이미지가 없을 때 처리
        if not img_area_elements:
            img_area_elements = driver.find_elements(By.XPATH, '//*[@id="productMainBody"]/div/div/div[3]/div/p/strong/img')
            if not img_area_elements:
                img_area_elements = driver.find_elements(By.XPATH, '//*[@id="productMainBody"]/div/div/div[4]/div/p/strong/img')
            # 이미지 저장
            image_list = []
            for i, img_element in enumerate(img_area_elements):
                img_url = img_element.get_attribute("src")
                img_data = urllib.request.urlopen(img_url).read()

                # 파일 이름 생성
                filename=title_element.text.replace('/', '_').replace(':', '_')
                file_name= filename+"_part"+str(i + 1)+".png"
                file_path = os.path.join(save_directory, file_name)

                # 이미지 저장
                with open(file_path, "wb") as file:
                    file.write(img_data)
                    print(f"Saved {file_name}")

        else:
            # 이미지가 있는 경우 처리 코드
        
            # 이미지 저장
            image_list = []
            for i, img_element in enumerate(img_area_elements):
                img_url = img_element.get_attribute("src")
                img_data = urllib.request.urlopen(img_url).read()

                # 파일 이름 생성
                filename=title_element.text.replace('/', '_').replace(':', '_')
                file_name= filename+"_part"+str(i + 1)+".png"
                file_path = os.path.join(save_directory, file_name)

                # 이미지 저장
                with open(file_path, "wb") as file:
                    file.write(img_data)
                    print(f"Saved {file_name}")
        
        #7.이미지에서 문자추출
        for i, img_element in enumerate(img_area_elements):
            img_text=[]
            img_name='D:/캡스톤 디자인/연극포스터/'+filename+"_part"+str(i + 1)+".png"
            img1=np.array(Image.open(img_name))
            text=pytesseract.image_to_string(img1,config='--psm 6 --oem 1',lang='kor')
            img_text.append(text)
            #img_text.append('\n')
            #img_text.append(text)
            
            scraped_image.append({'Title': title_element.text, 'Text':text})#,'img_URL': img_url})
            #print(text)
            
    return scraped_image
        
def save_to_csv(data_list, save_path):
    if data_list:
        combined_data = pd.DataFrame(data_list)
        combined_data.to_csv(save_path, index=False)

In [21]:
current_directory = os.getcwd()
save_path = os.path.join(current_directory, "D:/연극_ocr_전처리전_제목0.csv")

driver = initialize_driver()
query = "http://ticket.interpark.com/TPGoodsList.asp?Ca=Dra&Sort=3"
addresslist = get_theater_links(driver, query)
scraped_image = image(driver, addresslist,'D:/캡스톤 디자인/연극포스터/')
save_to_csv(scraped_image, save_path)
driver.quit()

Saved 연극 너의 목소리가 들려_part1.png
Saved 연극 너의 목소리가 들려_part2.png
Saved 연극 너의 목소리가 들려_part3.png
Saved 대학로 1위 연극 〈쉬어매드니스〉_part1.png
Saved 대학로 1위 연극 〈쉬어매드니스〉_part2.png
Saved 행오버_part1.png
Saved 행오버_part2.png
Saved 행오버_part3.png
Saved 행오버_part4.png
Saved 연극 〈바닷마을 다이어리〉_part1.png
Saved 연극 〈바닷마을 다이어리〉_part2.png
Saved 연극 한뼘사이_part1.png
Saved 연극 한뼘사이_part2.png
Saved 연극 한뼘사이_part3.png
Saved 연극 한뼘사이_part4.png
Saved 연극 한뼘사이_part5.png
Saved 연극 한뼘사이_part6.png
Saved 연극 한뼘사이_part7.png
Saved 연극 한뼘사이_part8.png
Saved 연극 한뼘사이_part9.png
Saved 연극 한뼘사이_part10.png
Saved 연극 한뼘사이_part11.png
Saved 연극 한뼘사이_part12.png
Saved 연극 한뼘사이_part13.png
Saved 연극 한뼘사이_part14.png
Saved 연극 한뼘사이_part15.png
Saved 연극〈늘근도둑이야기〉_part1.png
Saved 연극〈늘근도둑이야기〉_part2.png
Saved 뮤직드라마 〈불편한 편의점〉_part1.png
Saved 뮤직드라마 〈불편한 편의점〉_part2.png
Saved 뮤직드라마 〈불편한 편의점〉_part3.png
Saved 뮤직드라마 〈불편한 편의점〉_part4.png
Saved 뮤직드라마 〈불편한 편의점〉_part5.png
Saved 코믹감동 휴먼판타지 연극 〈2호선 세입자〉_part1.png
Saved 코믹감동 휴먼판타지 연극 〈2호선 세입자〉_part2.png
Saved 10년 연속 1위 연극〈옥탑방고양이〉- 틴틴홀_part1.png
Saved 10년 연속 1위 연극〈옥탑방고양이〉- 틴틴홀_part2.png
Saved 좀비연극 오마이갓_part1.png
Saved 좀비연극 오마이갓_part2.png
Saved 연극 핫식스_part1.png
Saved 연극 핫식스_part2.png
Saved ［서울 대학로］연극 라면_part1.png
Saved ［서울 대학로］연극 라면_part2.png
Saved 연극 〈기형도 플레이〉_part1.png
Saved 연극 죽여주는 이야기_part1.png
Saved 연극 〈카페 쥬에네스〉_part1.png
Saved 연극 〈카페 쥬에네스〉_part2.png
Saved 연극 〈운빨로맨스〉- 대학로_part1.png
Saved 연극 〈운빨로맨스〉- 대학로_part2.png
Saved 4D공포연극 〈스위치〉_part1.png
Saved 2023 연극 〈친정엄마와 2박 3일〉 - 고양_part1.png
Saved 국민 코믹 연극 〈오백에삼십〉 - 대학로 세우아트센터 1관_part1.png
Saved 국민 코믹 연극 〈오백에삼십〉 - 대학로 세우아트센터 1관_part2.png
Saved 국민 코믹 연극 〈오백에삼십〉 - 대학로 세우아트센터 1관_part3.png
Saved 연극 〈수상한흥신소〉_part1.png
Saved 연극 〈수상한흥신소〉_part2.png
Saved 연극 〈수상한흥신소〉_part3.png
Saved ［2023 SPAF］ 극단 돌파구 〈지상의 여자들〉_part1.png
Saved 러브 앤 인포메이션_part1.png
Saved 연극 〈뷰티풀라이프〉_part1.png
Saved 연극 〈뷰티풀라이프〉_part2.png
Saved 진짜나쁜소녀_part1.png
Saved 진짜나쁜소녀_part2.png
Saved 진짜나쁜소녀_part3.png
Saved 2023 연극 〈친정엄마와 2박 3일〉 - 군포_part1.png
Saved ★평점9.5★ 코미디의맛_쇼미더퍼니_part1.png
Saved ★평점9.5★ 코미디의맛_쇼미더퍼니_part2.png
Saved ★평점9.5★ 코미디의맛_쇼미더퍼니_part3.png
Saved 이머시브씨어터 카지노_part1.png
Saved 이머시브씨어터 카지노_part2.png
Saved 이머시브씨어터 카지노_part3.png
Saved 코미디 연극〈딜리버리〉_part1.png
Saved 코미디 연극〈딜리버리〉_part2.png
Saved 코미디 연극〈딜리버리〉_part3.png
Saved 2023년 연극 〈친정엄마와 2박3일 - 김해〉_part1.png
Saved 괴물B_part1.png
Saved 연극 〈굿닥터〉_part1.png
Saved 2시간탈출 졸탄쇼_part1.png
Saved 연극 〈극적인 하룻밤〉_part1.png
Saved 연극 〈극적인 하룻밤〉_part2.png
Saved 메이드 인 제인_part1.png
Saved 2023년 연극 〈친정엄마와 2박3일〉 - 용인_part1.png
Saved 연극 〈나의PS파트너〉_part1.png
Saved 연극 〈나의PS파트너〉_part2.png
Saved 연극 〈나의PS파트너〉_part3.png
Saved 제6회 1번출구 연극제 〈월드다방〉, 〈#정답을작성해주세요〉, 〈순례네 국밥〉_part1.png
Saved 공포연극 ［자취］_part1.png
Saved 공포연극 ［자취］_part2.png
Saved 공포연극 ［자취］_part3.png
Saved 연극 〈쉬어 매드니스(Shear Madness)〉 - 군포_part1.png
Saved 연극 〈슈만〉_part1.png
Saved 연극 〈슈만〉_part2.png
Saved !로맨틱코미디 연극〈운빨로맨스〉! - 대구_part1.png
Saved !로맨틱코미디 연극〈운빨로맨스〉! - 대구_part2.png
Saved !로맨틱코미디 연극〈운빨로맨스〉! - 대구_part3.png
Saved (리얼타임 코믹연극) 택시안에서 - 부산_part1.png
Saved (리얼타임 코믹연극) 택시안에서 - 부산_part2.png
Saved (리얼타임 코믹연극) 택시안에서 - 서울_part1.png
Saved (리얼타임 코믹연극) 택시안에서 - 서울_part2.png
Saved (코믹연극) 달동네-부산_part1.png
Saved (코믹연극) 달동네-부산_part2.png
Saved ［2023 SPAF］ 거인아트랩 〈인.투〉_part1.png
Saved ［2023 SPAF］ 구자하_캄포 〈하마티아 3부작_ 롤링 앤 롤링〉_part1.png
Saved ［2023 SPAF］ 구자하_캄포 〈하마티아 3부작_ 쿠쿠〉_part1.png
Saved ［2023 SPAF］ 구자하_캄포 〈하마티아 3부작_ 한국 연극의 역사〉_part1.png
Saved ［2023 SPAF］ 극단 골목길 〈이장〉_part1.png
Saved ［2023 SPAF］ 데드센터 〈베케트의 방〉_part1.png
Saved ［2023 SPAF］ 연극연습 프로젝트 〈연극연습3. 극작 연습-물고기로 죽기〉_part1.png
Saved ［2023 SPAF］ 작당모의 〈싸움의 기술, 〈졸〉_2.0〉_part1.png
Saved ［2023 SPAF］ 지연X전환 〈에너지_보이지 않는 언어〉_part1.png
Saved ［2023 SPAF］ 파이브 아트 센터 〈노셔널 히스토리〉_part1.png
Saved ［2023 SPAF］ SPAF 연극 패키지_part1.png
Saved ［2023 SPAF］ SPAF 하마티아 3부작 패키지_part1.png
Saved ［2023_셀러브리티 명품 로코］ 연극 이프온리 크리스마스특별 공연 - 울산_part1.png
Saved ［2023_셀러브리티 명품 로코］ 연극 이프온리 크리스마스특별 공연 _ 전주_part1.png
Saved ［2023_셀러브리티 명품 로코］연극 이프온리 크리스마스특별 공연 - 고양_part1.png
Saved ［2023_셀러브리티 명품 로코］연극 이프온리 크리스마스특별 공연 - 광주_part1.png
Saved ［2023_셀러브리티 명품 로코］연극 이프온리 크리스마스특별 공연 - 대구_part1.png
Saved ［2023_셀러브리티 명품 로코］연극 이프온리 크리스마스특별 공연 - 대전_part1.png
Saved ［2023_셀러브리티 명품 로코］연극 이프온리 크리스마스특별 공연 - 대학로_part1.png
Saved ［2023_셀러브리티 명품 로코］연극 이프온리 크리스마스특별 공연 - 인천_part1.png
Saved ［2023’셀러브리티 로코연극］러브액츄얼리 첫번째사연_크리스마스 특별공연 - 부산_part1.png
Saved ［연극 on stage］ 99% - 화성_part1.png
Saved ［연극 on stage］ 띨뿌리 - 화성_part1.png
Saved ［연극 on stage］ 띨뿌리 - 화성_part2.png
Saved ［연애하기 좋은 날 _ 당근거래］ - 전주_part1.png
Saved ［장애인 선예매］ 러브 앤 인포메이션_part1.png
Saved ［창작공감_ 연출］당신에게 닿는 길_part1.png
Saved ［청소년극］［Tank ; 0-24］_part1.png
Saved “뷰티풀라이프” - 대구_part1.png
Saved 〈#정답을작성해주세요〉 2023 제8회 청소년을 위한 공연예술축제(청공축제)_part1.png
Saved 〈봄의 주파수-트루헤르츠〉 제1회 웬연극 페스티벌_part1.png
Saved 〈소년소녀 모험백서〉 2023 제8회 청소년을 위한 공연예술축제(청공축제)_part1.png
Saved 〈에어컨 안은 뜨겁다〉 제1회 웬연극 페스티벌_part1.png
Saved 〈우호적인 작별파티〉 제1회 웬연극 페스티벌_part1.png
Saved 〈자전거 여행〉 2023 제8회 청소년을 위한 공연예술축제(청공축제)_part1.png
Saved 〈조씨고아, 복수의 씨앗〉 - 세종시_part1.png
Saved 〈지수가 누구야〉 2023 제8회 청소년을 위한 공연예술축제(청공축제)_part1.png
Saved 〈청혼, 곰〉 제1회 웬연극 페스티벌_part1.png
Saved 〈푸른 늑대의 후예〉 2023 제8회 청소년을 위한 공연예술축제(청공축제)_part1.png
Saved 〈하트비트〉 2023 제8회 청소년을 위한 공연예술축제(청공축제)_part1.png
Saved 〈환상통〉 제1회 웬연극 페스티벌_part1.png
Saved 〈The Most Boring Show in the World〉 2023 제8회 청소년을 위한 공연예술축제(청공축제)_part1.png
Saved 〈XXL레오타드 안나수이 손거울〉 2023 제8회 청소년을 위한 공연예술축제(청공축제)_part1.png
Saved 1초_part1.png
Saved 2023 〈목련 아래의 디오니소스〉 - 인천_part1.png
Saved 2023 공유생 리_바운드 프로젝트 연극 〈오늘도 극한직업〉_part1.png
Saved 2023 연극 〈친정엄마와2박3일〉 - 제주_part1.png
Saved 2023 연극 전태일_part1.png
Saved 2023 연극 전태일_part2.png
Saved 2023 연극 전태일_part3.png
Saved 2023 연극 전태일_part4.png
Saved 2023 연극 전태일_part5.png
Saved 2023 연극 전태일_part6.png
Saved 2023 연극 전태일 - 금천_part1.png
Saved 2023 연극 전태일 - 금천_part2.png
Saved 2023 연극 전태일 - 금천_part3.png
Saved 2023 연극 전태일 - 금천_part4.png
Saved 2023 연극 전태일 - 금천_part5.png
Saved 2023 연극 전태일 - 금천_part6.png
Saved 2023 연극만원(滿員)Ⅵ〈우리읍내〉_part1.png
Saved 2023 제작연극 헉슬리［멋진 신세계］-대전_part1.png
Saved 2023년 연극 〈친정엄마와 2박3일〉 - 당진_part1.png
Saved 2023놀자청년연극제_part1.png
Saved 2호선 세입자 - 연천_part1.png
Saved 3대가 웃고 우는 연극 〈염쟁이 유씨〉_part1.png
Saved 3일만 볼수있다면_part1.png
Saved 가장 아름다운 길 - 한예극장_part1.png
Saved 갈매기-목포의 눈물_part1.png
Saved 곡비_part1.png
Saved 공무도하_part1.png
Saved 공포스릴러연극〈두여자〉- 대구_part1.png
Saved 공포연극 조각_part1.png
Saved 공포연극 조각_part2.png
Saved 공포연극 조각_part3.png
Saved 괴물_part1.png
Saved 괴물_part2.png
Saved 괴물_part3.png
Saved 괴물_part4.png
Saved 괴물_part5.png
Saved 국립극장 기획 〈나는 재미있는 낙타예요〉_part1.png
Saved 국립극장 기획 〈나는 재미있는 낙타예요〉_part2.png
Saved 국민연극 〈라이어3탄 - 튀어 〉 광주_part1.png
Saved 국민연극 〈라이어3탄 - 튀어 〉 광주_part2.png
Saved 그곳에 있었다_part1.png
Saved 그곳에 있었다_part2.png
Saved 그날밤, 너랑나_part1.png
Saved 그녀를 용서할 수 있을까_part1.png
Saved 기승X결_part1.png
Saved 길 떠나는 고목_part1.png
Saved 길 떠나는 고목_part2.png
Saved 길 떠나는 고목_part3.png
Saved 길 떠나는 고목_part4.png
Saved 길 떠나는 고목_part5.png
Saved 깐돌이와 나_part1.png
Saved 꽃, 피우다_part1.png
Saved 나는 꽃이 싫다_part1.png
Saved 나의 장례식에 와줘_part1.png
Saved 나의 장례식에 와줘_part2.png
Saved 낙원상가_part1.png
Saved 낭땡이로 확 쳐불구정 허다 (나무 몽둥이로 확 때려버리고 싶다.)_part1.png
Saved 내 엄마 수연씨_part1.png
Saved 내 웨딩케이크는 누가 먹어버렸나_part1.png
Saved 넓은 하늘의 무지개를 보면 내 마음은 춤춘다-안산_part1.png
Saved 농토_part1.png
Saved 누구나 댄싱_part1.png
Saved 누구에게나 한번쯤 찾아오는 〈그날의,타이밍〉_B_part1.png
Saved 대구연극 〈오백에삼십〉 - 대구 동성로 아트플러스씨어터_part1.png
Saved 대학로 대표 로코 연극 〈그날의,타이밍〉_J_part1.png
Saved 대학로 청소년연극 〈사춘기메들리〉_part1.png
Saved 대학로 청소년연극 〈사춘기메들리〉_part2.png
Saved 대학로 청소년연극 〈사춘기메들리〉_part3.png
Saved 대학로 청소년연극 〈사춘기메들리〉_part4.png
Saved 더 클라운_부산국제공연예술마켓(BPAM)_part1.png
Saved 더 클라운_부산국제공연예술마켓(BPAM)_part2.png
Saved 데드센터 〈베케트의 방〉 - 세종시_part1.png
Saved 도가니 - 진주_part1.png
Saved 두 남자_part1.png
Saved 드립소년단_part1.png
Saved 뚜껑없는 열차_part1.png
Saved 뚜껑없는 열차_part2.png
Saved 뚜껑없는 열차_part3.png
Saved 뚜껑없는 열차_part4.png
Saved 뚜껑없는 열차_part5.png
Saved 뚜껑없는 열차_part6.png
Saved 뚜껑없는 열차_part7.png
Saved 뚜껑없는 열차_part8.png
Saved 레 미제라블, 용서의 이야기_part1.png
Saved 로맨틱연극［연애하기좋은날_당근거래］_part1.png
Saved 로맨틱코미디 〈슬기로운 신혼생활〉_part1.png
Saved 마담 칼리가리의 캐비넷_part1.png
Saved 마셴카 MASHENKA_part1.png
Saved 마셴카 MASHENKA_part2.png
Saved 마침표 - 군포_part1.png
Saved 명품 코믹 연극 〈죽여주는이야기〉 - 광주_part1.png
Saved 명품 코믹 연극 〈죽여주는이야기〉 - 광주_part2.png
Saved 모든 날 모든 순간_part1.png
Saved 모든 날 모든 순간_part2.png
Saved 모든 날 모든 순간_part3.png
Saved 무간도_part1.png
Saved 문화가 있는 날 Ⅳ NT Live［리어왕］- 대전_part1.png
Saved 뮤직드라마 〈망원동 브라더스〉_part1.png
Saved 뮤직드라마 〈망원동 브라더스〉_part2.png
Saved 뮤직드라마 〈망원동 브라더스〉_part3.png
Saved 민초_part1.png

In [22]:
a=pd.read_csv("D:/연극_ocr_전처리전_제목0.csv")
a

,Title,Text
0,연극 너의 목소리가 들려,"0] 임이 79 90890 0000\n` 머크 <터의[목소리[""들려/ 대\n』 ..."
1,연극 너의 목소리가 들려,"@\n> `\n2\n1 >\n“> ㅜ\n, ..."
2,연극 너의 목소리가 들려,ㅇ\n1077\n2100 430 6130\n박선영 박선영 피설아 : 아 인 아 인 ...
3,대학로 1위 연극 〈쉬어매드니스〉,”-- -ㅋ- =\n콘텐츠박스 ...
4,대학로 1위 연극 〈쉬어매드니스〉,오이타 내더연어\n그 오소시 거으가\n.0010066 10월\n...
...,...,...
240,문화가 있는 날 Ⅳ NT Live［리어왕］- 대전,"트는 0"" _ 내\n ..."
241,뮤직드라마 〈망원동 브라더스〉,고 는 그노든(| 돋 |[.왔 [\n골때리는 그놈들이 돌.마왔다!\n ...
242,뮤직드라마 〈망원동 브라더스〉,1.00210700\n-오시는킬-\n서울특별시 마포구 어울마당로 94-8 61 제이...
243,뮤직드라마 〈망원동 브라더스〉,원작 김호연 작가 밀리언셀러 “불편한 편의점*이 공연으로 재탄생\n\n뮤직드라마 ...
244,민초,> 개 사이 3} 그 : 겹 에 조 : 련 로 주 로 1\n니 8040디시 이...

In [23]:
result_df = a.groupby("Title")["Text"].apply(lambda x: "\n".join(x)).reset_index()
result_df

,Title,Text
0,!로맨틱코미디 연극〈운빨로맨스〉! - 대구,| = [그 ...
1,(리얼타임 코믹연극) 택시안에서 - 부산,"、 、 웃음, 감동, 사랑이 시작되는 리얼타엄 코믹연극\n2019.03.15680)..."
2,(리얼타임 코믹연극) 택시안에서 - 서울,ㆍ ㆍ ㆍ 0” 로 변\...
3,(코믹연극) 달동네-부산,0 ~ 20006 웅새떼스 026 토\n그 206 6: 버 ~? ...
4,10년 연속 1위 연극〈옥탑방고양이〉- 틴틴홀,가을 바람 살학살항\n뼈 |\n로맨틱\n|\n205\n10넌 연숙 ...
...,...,...
141,［연극 on stage］ 띨뿌리 - 화성,"크 의닝 아Ｌ 1\n\n트리거워닝안내 ” ㅠㅠ ~,\n\n연극 <떨뿌리..."
142,［연애하기 좋은 날 : 당근거래］ - 전주,"~ 오 100 ^ 1\n. -헤\n개 |"" 0 ..."
143,［장애인 선예매］ 러브 앤 인포메이션,...
144,［창작공감: 연출］당신에게 닿는 길,9 홍익대대학로 작연출:\...
145,［청소년극］［Tank ; 0-24］,14 국립극단 구성미술연출:\n0ㅁ미 ...

In [24]:
def initialize_driver():
    chrome_options = webdriver.ChromeOptions()
    driver = webdriver.Chrome(service=Service('D:\chromedriver-win32\chromedriver.exe'), options=chrome_options)
    return driver

def get_theater_links(driver, query):
    driver.get(query)
    time.sleep(1)
    number = 160

    addresslist = []

    for i in range(1, int(number) + 1):
        xpath = f"/html/body/table/tbody/tr[2]/td[3]/div/div/div[2]/div/table/tbody/tr[{i}]/td[1]/a"
        elem = driver.find_element(By.XPATH, xpath).get_attribute("href")
        addresslist.append(elem)

    return addresslist


def resize_image(image, max_height):
    # 이미지 크기를 최대 높이에 맞춰 조정
    width_percent = (max_height / float(image.size[1]))
    new_width = int((float(image.size[0]) * float(width_percent)))
    resized_image = image.resize((new_width, max_height), Image.LANCZOS)
    return resized_image

def image(driver, addresslist, save_directory, max_image_height=2000):
    scraped_image = []
    for index, lis in enumerate(addresslist):
        driver.get(lis)
        time.sleep(1)
        
        # 이미지 요소 찾기
        img_area_elements = driver.find_elements(By.XPATH, '//*[@id="productMainBody"]/div/div/div[5]/div/p/strong/img')
        title_element = driver.find_element(By.XPATH, '//*[@id="container"]/div[5]/div[1]/div[2]/div[1]/div/div[1]/h2')
        
        # 이미지가 없을 때 처리
        if not img_area_elements:
            img_area_elements = driver.find_elements(By.XPATH, '//*[@id="productMainBody"]/div/div/div[3]/div/p/strong/img')
            if not img_area_elements:
                img_area_elements = driver.find_elements(By.XPATH, '//*[@id="productMainBody"]/div/div/div[4]/div/p/strong/img')
            # 이미지 저장
            image_list = []
            for i, img_element in enumerate(img_area_elements):
                img_url = img_element.get_attribute("src")
                img_data = urllib.request.urlopen(img_url).read()

                # 파일 이름 생성
                filename=title_element.text.replace('/', '_').replace(':', '_')
                file_name= filename+"_part"+str(i + 1)+".png"
                file_path = os.path.join(save_directory, file_name)

                # 이미지 저장
                with open(file_path, "wb") as file:
                    file.write(img_data)
                    print(f"Saved {file_name}")

        else:
            # 이미지가 있는 경우 처리 코드
        
            # 이미지 저장
            image_list = []
            for i, img_element in enumerate(img_area_elements):
                img_url = img_element.get_attribute("src")
                img_data = urllib.request.urlopen(img_url).read()

                # 파일 이름 생성
                filename=title_element.text.replace('/', '_').replace(':', '_')
                file_name= filename+"_part"+str(i + 1)+".png"
                file_path = os.path.join(save_directory, file_name)

                # 이미지 저장
                with open(file_path, "wb") as file:
                    file.write(img_data)
                    print(f"Saved {file_name}")
        
        #7.이미지에서 문자추출
        for i, img_element in enumerate(img_area_elements):
            img_text=[]
            img_name='D:/캡스톤 디자인/연극포스터/'+filename+"_part"+str(i + 1)+".png"
            img1=np.array(Image.open(img_name))
            text=pytesseract.image_to_string(img1,config='--psm 6 --oem 1',lang='kor')
            img_text.append(text)
            #img_text.append('\n')
            #img_text.append(text)
            
            scraped_image.append({'Title': title_element.text, 'Text':text})#,'img_URL': img_url})
            #print(text)
            
    return scraped_image
        
def save_to_csv(data_list, save_path):
    if data_list:
        combined_data = pd.DataFrame(data_list)
        combined_data.to_csv(save_path, index=False)

In [25]:
current_directory = os.getcwd()
save_path = os.path.join(current_directory, "D:/연극_ocr_전처리전_제목160.csv")

driver = initialize_driver()
query = "http://ticket.interpark.com/TPGoodsList.asp?Ca=Dra&Sort=3"
addresslist = get_theater_links(driver, query)
scraped_image = image(driver, addresslist,'D:/캡스톤 디자인/연극포스터/')
save_to_csv(scraped_image, save_path)
driver.quit()

Saved 연극 너의 목소리가 들려_part1.png
Saved 연극 너의 목소리가 들려_part2.png
Saved 연극 너의 목소리가 들려_part3.png
Saved 대학로 1위 연극 〈쉬어매드니스〉_part1.png
Saved 대학로 1위 연극 〈쉬어매드니스〉_part2.png
Saved 행오버_part1.png
Saved 행오버_part2.png
Saved 행오버_part3.png
Saved 행오버_part4.png
Saved 연극 〈바닷마을 다이어리〉_part1.png
Saved 연극 〈바닷마을 다이어리〉_part2.png
Saved 연극 한뼘사이_part1.png
Saved 연극 한뼘사이_part2.png
Saved 연극 한뼘사이_part3.png
Saved 연극 한뼘사이_part4.png
Saved 연극 한뼘사이_part5.png
Saved 연극 한뼘사이_part6.png
Saved 연극 한뼘사이_part7.png
Saved 연극 한뼘사이_part8.png
Saved 연극 한뼘사이_part9.png
Saved 연극 한뼘사이_part10.png
Saved 연극 한뼘사이_part11.png
Saved 연극 한뼘사이_part12.png
Saved 연극 한뼘사이_part13.png
Saved 연극 한뼘사이_part14.png
Saved 연극 한뼘사이_part15.png
Saved 연극〈늘근도둑이야기〉_part1.png
Saved 연극〈늘근도둑이야기〉_part2.png
Saved 뮤직드라마 〈불편한 편의점〉_part1.png
Saved 뮤직드라마 〈불편한 편의점〉_part2.png
Saved 뮤직드라마 〈불편한 편의점〉_part3.png
Saved 뮤직드라마 〈불편한 편의점〉_part4.png
Saved 뮤직드라마 〈불편한 편의점〉_part5.png
Saved 코믹감동 휴먼판타지 연극 〈2호선 세입자〉_part1.png
Saved 코믹감동 휴먼판타지 연극 〈2호선 세입자〉_part2.png
Saved 10년 연속 1위 연극〈옥탑방고양이〉- 틴틴홀_part1.png
Saved 10년 연속 1위 연극〈옥탑방고양이〉- 틴틴홀_part2.png
Saved 좀비연극 오마이갓_part1.png
Saved 좀비연극 오마이갓_part2.png
Saved 연극 핫식스_part1.png
Saved 연극 핫식스_part2.png
Saved ［서울 대학로］연극 라면_part1.png
Saved ［서울 대학로］연극 라면_part2.png
Saved 연극 〈기형도 플레이〉_part1.png
Saved 연극 죽여주는 이야기_part1.png
Saved 연극 〈카페 쥬에네스〉_part1.png
Saved 연극 〈카페 쥬에네스〉_part2.png
Saved 연극 〈운빨로맨스〉- 대학로_part1.png
Saved 연극 〈운빨로맨스〉- 대학로_part2.png
Saved 4D공포연극 〈스위치〉_part1.png
Saved 2023 연극 〈친정엄마와 2박 3일〉 - 고양_part1.png
Saved 국민 코믹 연극 〈오백에삼십〉 - 대학로 세우아트센터 1관_part1.png
Saved 국민 코믹 연극 〈오백에삼십〉 - 대학로 세우아트센터 1관_part2.png
Saved 국민 코믹 연극 〈오백에삼십〉 - 대학로 세우아트센터 1관_part3.png
Saved 연극 〈수상한흥신소〉_part1.png
Saved 연극 〈수상한흥신소〉_part2.png
Saved 연극 〈수상한흥신소〉_part3.png
Saved ［2023 SPAF］ 극단 돌파구 〈지상의 여자들〉_part1.png
Saved 러브 앤 인포메이션_part1.png
Saved 연극 〈뷰티풀라이프〉_part1.png
Saved 연극 〈뷰티풀라이프〉_part2.png
Saved 진짜나쁜소녀_part1.png
Saved 진짜나쁜소녀_part2.png
Saved 진짜나쁜소녀_part3.png
Saved 2023 연극 〈친정엄마와 2박 3일〉 - 군포_part1.png
Saved ★평점9.5★ 코미디의맛_쇼미더퍼니_part1.png
Saved ★평점9.5★ 코미디의맛_쇼미더퍼니_part2.png
Saved ★평점9.5★ 코미디의맛_쇼미더퍼니_part3.png
Saved 이머시브씨어터 카지노_part1.png
Saved 이머시브씨어터 카지노_part2.png
Saved 이머시브씨어터 카지노_part3.png
Saved 코미디 연극〈딜리버리〉_part1.png
Saved 코미디 연극〈딜리버리〉_part2.png
Saved 코미디 연극〈딜리버리〉_part3.png
Saved 2023년 연극 〈친정엄마와 2박3일 - 김해〉_part1.png
Saved 괴물B_part1.png
Saved 연극 〈굿닥터〉_part1.png
Saved 2시간탈출 졸탄쇼_part1.png
Saved 연극 〈극적인 하룻밤〉_part1.png
Saved 연극 〈극적인 하룻밤〉_part2.png
Saved 메이드 인 제인_part1.png
Saved 2023년 연극 〈친정엄마와 2박3일〉 - 용인_part1.png
Saved 연극 〈나의PS파트너〉_part1.png
Saved 연극 〈나의PS파트너〉_part2.png
Saved 연극 〈나의PS파트너〉_part3.png
Saved 제6회 1번출구 연극제 〈월드다방〉, 〈#정답을작성해주세요〉, 〈순례네 국밥〉_part1.png
Saved 공포연극 ［자취］_part1.png
Saved 공포연극 ［자취］_part2.png
Saved 공포연극 ［자취］_part3.png
Saved 연극 〈쉬어 매드니스(Shear Madness)〉 - 군포_part1.png
Saved 연극 〈슈만〉_part1.png
Saved 연극 〈슈만〉_part2.png
Saved !로맨틱코미디 연극〈운빨로맨스〉! - 대구_part1.png
Saved !로맨틱코미디 연극〈운빨로맨스〉! - 대구_part2.png
Saved !로맨틱코미디 연극〈운빨로맨스〉! - 대구_part3.png
Saved (리얼타임 코믹연극) 택시안에서 - 부산_part1.png
Saved (리얼타임 코믹연극) 택시안에서 - 부산_part2.png
Saved (리얼타임 코믹연극) 택시안에서 - 서울_part1.png
Saved (리얼타임 코믹연극) 택시안에서 - 서울_part2.png
Saved (코믹연극) 달동네-부산_part1.png
Saved (코믹연극) 달동네-부산_part2.png
Saved ［2023 SPAF］ 거인아트랩 〈인.투〉_part1.png
Saved ［2023 SPAF］ 구자하_캄포 〈하마티아 3부작_ 롤링 앤 롤링〉_part1.png
Saved ［2023 SPAF］ 구자하_캄포 〈하마티아 3부작_ 쿠쿠〉_part1.png
Saved ［2023 SPAF］ 구자하_캄포 〈하마티아 3부작_ 한국 연극의 역사〉_part1.png
Saved ［2023 SPAF］ 극단 골목길 〈이장〉_part1.png
Saved ［2023 SPAF］ 데드센터 〈베케트의 방〉_part1.png
Saved ［2023 SPAF］ 연극연습 프로젝트 〈연극연습3. 극작 연습-물고기로 죽기〉_part1.png
Saved ［2023 SPAF］ 작당모의 〈싸움의 기술, 〈졸〉_2.0〉_part1.png
Saved ［2023 SPAF］ 지연X전환 〈에너지_보이지 않는 언어〉_part1.png
Saved ［2023 SPAF］ 파이브 아트 센터 〈노셔널 히스토리〉_part1.png
Saved ［2023 SPAF］ SPAF 연극 패키지_part1.png
Saved ［2023 SPAF］ SPAF 하마티아 3부작 패키지_part1.png
Saved ［2023_셀러브리티 명품 로코］ 연극 이프온리 크리스마스특별 공연 - 울산_part1.png
Saved ［2023_셀러브리티 명품 로코］ 연극 이프온리 크리스마스특별 공연 _ 전주_part1.png
Saved ［2023_셀러브리티 명품 로코］연극 이프온리 크리스마스특별 공연 - 고양_part1.png
Saved ［2023_셀러브리티 명품 로코］연극 이프온리 크리스마스특별 공연 - 광주_part1.png
Saved ［2023_셀러브리티 명품 로코］연극 이프온리 크리스마스특별 공연 - 대구_part1.png
Saved ［2023_셀러브리티 명품 로코］연극 이프온리 크리스마스특별 공연 - 대전_part1.png
Saved ［2023_셀러브리티 명품 로코］연극 이프온리 크리스마스특별 공연 - 대학로_part1.png
Saved ［2023_셀러브리티 명품 로코］연극 이프온리 크리스마스특별 공연 - 인천_part1.png
Saved ［2023’셀러브리티 로코연극］러브액츄얼리 첫번째사연_크리스마스 특별공연 - 부산_part1.png
Saved ［연극 on stage］ 99% - 화성_part1.png
Saved ［연극 on stage］ 띨뿌리 - 화성_part1.png
Saved ［연극 on stage］ 띨뿌리 - 화성_part2.png
Saved ［연애하기 좋은 날 _ 당근거래］ - 전주_part1.png
Saved ［장애인 선예매］ 러브 앤 인포메이션_part1.png
Saved ［창작공감_ 연출］당신에게 닿는 길_part1.png
Saved ［청소년극］［Tank ; 0-24］_part1.png
Saved “뷰티풀라이프” - 대구_part1.png
Saved 〈#정답을작성해주세요〉 2023 제8회 청소년을 위한 공연예술축제(청공축제)_part1.png
Saved 〈봄의 주파수-트루헤르츠〉 제1회 웬연극 페스티벌_part1.png
Saved 〈소년소녀 모험백서〉 2023 제8회 청소년을 위한 공연예술축제(청공축제)_part1.png
Saved 〈에어컨 안은 뜨겁다〉 제1회 웬연극 페스티벌_part1.png
Saved 〈우호적인 작별파티〉 제1회 웬연극 페스티벌_part1.png
Saved 〈자전거 여행〉 2023 제8회 청소년을 위한 공연예술축제(청공축제)_part1.png
Saved 〈조씨고아, 복수의 씨앗〉 - 세종시_part1.png
Saved 〈지수가 누구야〉 2023 제8회 청소년을 위한 공연예술축제(청공축제)_part1.png
Saved 〈청혼, 곰〉 제1회 웬연극 페스티벌_part1.png
Saved 〈푸른 늑대의 후예〉 2023 제8회 청소년을 위한 공연예술축제(청공축제)_part1.png
Saved 〈하트비트〉 2023 제8회 청소년을 위한 공연예술축제(청공축제)_part1.png
Saved 〈환상통〉 제1회 웬연극 페스티벌_part1.png
Saved 〈The Most Boring Show in the World〉 2023 제8회 청소년을 위한 공연예술축제(청공축제)_part1.png
Saved 〈XXL레오타드 안나수이 손거울〉 2023 제8회 청소년을 위한 공연예술축제(청공축제)_part1.png
Saved 1초_part1.png
Saved 2023 〈목련 아래의 디오니소스〉 - 인천_part1.png
Saved 2023 공유생 리_바운드 프로젝트 연극 〈오늘도 극한직업〉_part1.png
Saved 2023 연극 〈친정엄마와2박3일〉 - 제주_part1.png
Saved 2023 연극 전태일_part1.png
Saved 2023 연극 전태일_part2.png
Saved 2023 연극 전태일_part3.png
Saved 2023 연극 전태일_part4.png
Saved 2023 연극 전태일_part5.png
Saved 2023 연극 전태일_part6.png
Saved 2023 연극 전태일 - 금천_part1.png
Saved 2023 연극 전태일 - 금천_part2.png
Saved 2023 연극 전태일 - 금천_part3.png
Saved 2023 연극 전태일 - 금천_part4.png
Saved 2023 연극 전태일 - 금천_part5.png
Saved 2023 연극 전태일 - 금천_part6.png
Saved 2023 연극만원(滿員)Ⅵ〈우리읍내〉_part1.png
Saved 2023 제작연극 헉슬리［멋진 신세계］-대전_part1.png
Saved 2023년 연극 〈친정엄마와 2박3일〉 - 당진_part1.png
Saved 2023놀자청년연극제_part1.png
Saved 2호선 세입자 - 연천_part1.png
Saved 3대가 웃고 우는 연극 〈염쟁이 유씨〉_part1.png
Saved 3일만 볼수있다면_part1.png
Saved 가장 아름다운 길 - 한예극장_part1.png
Saved 갈매기-목포의 눈물_part1.png
Saved 곡비_part1.png
Saved 공무도하_part1.png
Saved 공포스릴러연극〈두여자〉- 대구_part1.png
Saved 공포연극 조각_part1.png
Saved 공포연극 조각_part2.png
Saved 공포연극 조각_part3.png
Saved 괴물_part1.png
Saved 괴물_part2.png
Saved 괴물_part3.png
Saved 괴물_part4.png
Saved 괴물_part5.png
Saved 국립극장 기획 〈나는 재미있는 낙타예요〉_part1.png
Saved 국립극장 기획 〈나는 재미있는 낙타예요〉_part2.png
Saved 국민연극 〈라이어3탄 - 튀어 〉 광주_part1.png
Saved 국민연극 〈라이어3탄 - 튀어 〉 광주_part2.png
Saved 그곳에 있었다_part1.png
Saved 그곳에 있었다_part2.png
Saved 그날밤, 너랑나_part1.png
Saved 그녀를 용서할 수 있을까_part1.png
Saved 기승X결_part1.png
Saved 길 떠나는 고목_part1.png
Saved 길 떠나는 고목_part2.png
Saved 길 떠나는 고목_part3.png
Saved 길 떠나는 고목_part4.png
Saved 길 떠나는 고목_part5.png
Saved 깐돌이와 나_part1.png
Saved 꽃, 피우다_part1.png
Saved 나는 꽃이 싫다_part1.png
Saved 나의 장례식에 와줘_part1.png
Saved 나의 장례식에 와줘_part2.png
Saved 낙원상가_part1.png
Saved 낭땡이로 확 쳐불구정 허다 (나무 몽둥이로 확 때려버리고 싶다.)_part1.png
Saved 내 엄마 수연씨_part1.png
Saved 내 웨딩케이크는 누가 먹어버렸나_part1.png
Saved 넓은 하늘의 무지개를 보면 내 마음은 춤춘다-안산_part1.png
Saved 농토_part1.png
Saved 누구나 댄싱_part1.png
Saved 누구에게나 한번쯤 찾아오는 〈그날의,타이밍〉_B_part1.png
Saved 대구연극 〈오백에삼십〉 - 대구 동성로 아트플러스씨어터_part1.png
Saved 대학로 대표 로코 연극 〈그날의,타이밍〉_J_part1.png
Saved 대학로 청소년연극 〈사춘기메들리〉_part1.png
Saved 대학로 청소년연극 〈사춘기메들리〉_part2.png
Saved 대학로 청소년연극 〈사춘기메들리〉_part3.png
Saved 대학로 청소년연극 〈사춘기메들리〉_part4.png
Saved 더 클라운_부산국제공연예술마켓(BPAM)_part1.png
Saved 더 클라운_부산국제공연예술마켓(BPAM)_part2.png
Saved 데드센터 〈베케트의 방〉 - 세종시_part1.png
Saved 도가니 - 진주_part1.png
Saved 두 남자_part1.png
Saved 드립소년단_part1.png
Saved 뚜껑없는 열차_part1.png
Saved 뚜껑없는 열차_part2.png
Saved 뚜껑없는 열차_part3.png
Saved 뚜껑없는 열차_part4.png
Saved 뚜껑없는 열차_part5.png
Saved 뚜껑없는 열차_part6.png
Saved 뚜껑없는 열차_part7.png
Saved 뚜껑없는 열차_part8.png
Saved 레 미제라블, 용서의 이야기_part1.png
Saved 로맨틱연극［연애하기좋은날_당근거래］_part1.png
Saved 로맨틱코미디 〈슬기로운 신혼생활〉_part1.png
Saved 마담 칼리가리의 캐비넷_part1.png
Saved 마셴카 MASHENKA_part1.png
Saved 마셴카 MASHENKA_part2.png
Saved 마침표 - 군포_part1.png
Saved 명품 코믹 연극 〈죽여주는이야기〉 - 광주_part1.png
Saved 명품 코믹 연극 〈죽여주는이야기〉 - 광주_part2.png
Saved 모든 날 모든 순간_part1.png
Saved 모든 날 모든 순간_part2.png
Saved 모든 날 모든 순간_part3.png
Saved 무간도_part1.png
Saved 문화가 있는 날 Ⅳ NT Live［리어왕］- 대전_part1.png
Saved 뮤직드라마 〈망원동 브라더스〉_part1.png
Saved 뮤직드라마 〈망원동 브라더스〉_part2.png
Saved 뮤직드라마 〈망원동 브라더스〉_part3.png
Saved 민초_part1.png
Saved 봄이 오면_part1.png
Saved 부동산 오브 슈퍼맨_part1.png
Saved 뷰티풀라이프 - 천안_part1.png
Saved 비누향기_part1.png
Saved 비누향기_part2.png
Saved 비누향기_part3.png
Saved 비누향기_part4.png
Saved 비누향기_part5.png
Saved 비누향기_part6.png
Saved 샤프심_part1.png
Saved 서교동에서 죽다 - 서울 꿈빛극장_part1.png
Saved 섬_part1.png
Saved 섹시코미디연극 나의PS파트너 (청주)_part1.png
Saved 쇼팔다 미친 유령 극단_part1.png
Saved 스쁘라브카-열람_part1.png

In [26]:
a=pd.read_csv("D:/연극_ocr_전처리전_제목160.csv")
a

                    Title                                               Text
0           연극 너의 목소리가 들려  0] 임이 79 90890 0000\n` 머크 <터의[목소리["들려/   대\n』 ...
1           연극 너의 목소리가 들려  @\n> `\n2\n1                     >\n“>   ㅜ\n, ...
2           연극 너의 목소리가 들려  ㅇ\n1077\n2100 430 6130\n박선영 박선영 피설아 : 아 인 아 인 ...
3      대학로 1위 연극 〈쉬어매드니스〉  ”-- -ㅋ- =\n콘텐츠박스                              ...
4      대학로 1위 연극 〈쉬어매드니스〉  오이타            내더연어\n그 오소시 거으가\n.0010066 10월\n...
..                    ...                                                ...
255    서교동에서 죽다 - 서울 꿈빛극장  가 ~ ~         …~\n-  “"% ㅋ\n주        ~        ...
256                     섬  @                           '                 ...
257  섹시코미디연극 나의PS파트너 (청주)  때  다 이   [   1\n내가 그 날 열마Ｌ\n~               『\...
258          쇼팔다 미친 유령 극단  8 마지막 주, 10잇 번페 주 공연 없음\n2023년 9월 1일부터 10월 15일...
259              스쁘라브카-열람                  [\n) = (^      [수\n,\n：   ~” 게스\n

[260 rows x 2 columns]

In [27]:
result_df = a.groupby("Title")["Text"].apply(lambda x: "\n".join(x)).reset_index()
result_df

,Title,Text
0,!로맨틱코미디 연극〈운빨로맨스〉! - 대구,| = [그 ...
1,(리얼타임 코믹연극) 택시안에서 - 부산,"、 、 웃음, 감동, 사랑이 시작되는 리얼타엄 코믹연극\n2019.03.15680)..."
2,(리얼타임 코믹연극) 택시안에서 - 서울,ㆍ ㆍ ㆍ 0” 로 변\...
3,(코믹연극) 달동네-부산,0 ~ 20006 웅새떼스 026 토\n그 206 6: 버 ~? ...
4,10년 연속 1위 연극〈옥탑방고양이〉- 틴틴홀,가을 바람 살학살항\n뼈 |\n로맨틱\n|\n205\n10넌 연숙 ...
...,...,...
151,［연극 on stage］ 띨뿌리 - 화성,"크 의닝 아Ｌ 1\n\n트리거워닝안내 ” ㅠㅠ ~,\n\n연극 <떨뿌리..."
152,［연애하기 좋은 날 : 당근거래］ - 전주,"~ 오 100 ^ 1\n. -헤\n개 |"" 0 ..."
153,［장애인 선예매］ 러브 앤 인포메이션,...
154,［창작공감: 연출］당신에게 닿는 길,9 홍익대대학로 작연출:\...
155,［청소년극］［Tank ; 0-24］,14 국립극단 구성미술연출:\n0ㅁ미 ...